main = print $ "Peteco"
minimum = min 7 9
maximum = max 3 Main.minimum
combined = (succ 9) + (max 5 4) + 1
integralDivision = div 92 10
integralDivision' = 92 `div` 10
doubleMe x = x + x
doubleUs x y = doubleMe x + doubleMe y
doubleSmallNumber x = if x > 100 then x else x * 2
doubleSmallNumber' x = (if x > 100 then x else x * 2) + 1
conanO'Brien = "It's a-me, Conan O'Brien!"
